seatalk_test: seatalk_test.c assertions.c seatalk_hardware_layer.c seatalk_transport_layer.c seatalk_state.c seatalk_datagram.c seatalk_command.c
	cc -o seatalk_test seatalk_test.c seatalk_transport_layer.c seatalk_state.c seatalk_hardware_layer.c seatalk_datagram.c assertions.c seatalk_command.c -I.
