int get_command_datagram(char *datagram);
int seatalk_command_pending(void);
//void send_command(int length);
int set_lamp_intensity(int level);
//void cancel_mob(void);
//void track_keystroke_from_gps(void);
//void set_countdown_timer(int minutes, int seconds, int hours, int mode);
//void acknowledge_alarm(int alarm_type);
//void mob(void);
//void maxview_remote_keypress(ST_AUTOPILOT_COMMAND command);
//void pass_user_cal(void);
int autopilot_remote_keystroke(ST_AUTOPILOT_COMMAND command);
int set_autopilot_response_level(AUTOPILOT_RESPONSE_LEVEL level);
//void set_autopilot_rudder_gain(int level);
//void set_autopilot_parameter(int parameter_number, int value);
