#!/bin/sh

# Run this script using sudo and with your SeaTalk level translator
# hardware plugged in to test the full communication suite system.

insmod ../seatalk.ko
for heading in 0 9 29 101 157 187 210 300 315 330 341 350 359
do
  echo "$heading" > /sys/seatalk/sensors/heading
  sleep 0.5
  status_heading=`cat /sys/seatalk/status/heading`
  if [ "$heading" != "$status_heading" ]; then
    echo "failed to propagate heading sensor value sent ($heading) to status/heading received ($status_heading)"
  fi
done

#for intensity in 0 1 2 3
#do
#  echo "$intensity" > /sys/seatalk/commands/set_lamp_intensity
#  sleep 0.25
#  $status_intensity = `cat /sys/seatalk/systus/lamp_intensity`
#  if [ $intensity != $status_intensity ]; then
#    echo "failed to propagate lamp intensity command ($intensity) to status/lamp_intensity ($status_intensity)"
#  fi
#done

rmmod ../seatalk.ko
